### ISSUE TITLE
unable to load none default scm provider

### ISSUE THREAD

**Issue by dantran** [khmarbaise/incremental-module-builder#4]
encounter this error

[INFO] Not executing in root.
[ERROR] Failure during makeScmRepository
org.apache.maven.scm.manager.NoSuchScmProviderException: No such provider: 'p4'.
	at org.apache.maven.scm.manager.AbstractScmManager.getProviderByType(AbstractScmManager.java:168)
	at org.apache.maven.scm.manager.AbstractScmManager.makeScmRepository(AbstractScmManager.java:202)
	at com.soebes.maven.extensions.incremental.IncrementalModuleBuilder.build(IncrementalModuleBuilder.java:111)

I do have maven-scm-plugin plugigMangement does include p4maven provider

**Comment by khmarbaise** [comment]
If I correctly remember the provider needs to be named `perforce`?

**Comment by dantran** [comment]
'perforce' is the abandon CLI provider(still under maven-scm).  I now use p4maven(pure java provider) from Perforce ( I implemented for them) and p4 name of the java proviver

**Comment by khmarbaise** [comment]
Ah I didn't know that...I currently using the SCM API nothing more at the moment....Does that mean your configuration usually works with Maven SCM / Maven Release Plugin ? May be I need to improve this in my extension...Do you have an example project which shows the correct looking provider and configuration in your pom file?

**Comment by dantran** [comment]
yes, i am using maven release plugin to do release work

here is sample maven-scm url scm:p4:workshop.perforce.com:1666://guest/dantran/p4maven

but you need this pom http://central.maven.org/maven2/com/perforce/p4maven/p4maven/1.0.6/p4maven-1.0.6.pom to do the checkout out/export

may be I need to include the p4maven provider with your extension

**Comment by dantran** [comment]
please include to your pom, and cut a release I will try to use it

<dependencies>
<dependency>
<groupId>com.perforce.p4maven</groupId>
<artifactId>p4maven-provider</artifactId>
<version>1.0.6</version>
</dependency>
</dependencies>

**Comment by dantran** [comment]
btw, my module names and artifactId dont normally match. Would this work with your extension?

**Comment by khmarbaise** [comment]
Made a new release 0.2.0 may be you can check if it works for you...

**Comment by dantran** [comment]
it is at maven central yet

**Comment by khmarbaise** [comment]
Sorry forgot the release the staging repo on...will take some time...

**Comment by dantran** [comment]
I got further. But the build does not detect change.  my project consist of multiple modules (maven plugins) each has its own release cycle ( version).  

I will try other projects all modules has the same version as top parent

Your work has a huge potential thou
