### ISSUE TITLE
Unable to execute mvn -b incremental package cmd?

### ISSUE THREAD

**Issue by karunakar1122v** [khmarbaise/incremental-module-builder#5]
When I execute mvn -b incremental package cmd always its skipped all modules.
But I changed files in one module.Dont know y its skipped all modules>can you please let me know what was the issue?

**Comment by khmarbaise** [comment]
Can you post a full log output?

**Comment by karunakar1122v** [comment]
Hi,

Issue resolved.
Thanks for your response.

Thanks & Regards
Karunakar

**Comment by khmarbaise** [comment]
What was the problem? How did you solve it?

**Comment by karunakar1122v** [comment]
Hi,

I configured extensions.xml in my project. But without adding incremental maven builder  dependency in pom.xml  I had executed. because of this its given error.

Thanks & Regards
Karunakar

**Comment by khmarbaise** [comment]
Only configuring extensions.xml in the `.mvn/extensions.xml` files is necessary with Maven 3.3.1+ nothing else is needed...

**Comment by vicmosin** [comment]
Did not work to me as well, since your readme mentions `0.3.0` version which isn't exist. Once I used `0.2.0` in extensions.xml -> CLI worked fine

**Comment by khmarbaise** [comment]
Yeah my fault, cause 0.3.0 is not yet released ;-(
