### ISSUE TITLE
Flat Multi Module Project

### ISSUE THREAD

**Issue by gtnarg** [khmarbaise/incremental-module-builder#9]
Does this support a structure where the module projects exist is at the same level as the aggregate pom?

For example:

```
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.sample</groupId>
    <artifactId>project</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>../module-1</module>
        <module>../module-2</module>
        <module>../module-n</module>
    </modules>
</project>
```

**Comment by khmarbaise** [comment]
Have you tried it ?

**Comment by gtnarg** [comment]
I was hoping for a quick response before investing time into something that wasn't designed for my use case so unfortunately moved on with my own solution.  My assumption, is that you are depending on an svn change in the root project vs checking each child project separately (correct me if I'm wrong).  That unfortunately won't work for my use case.

Thanks
